### ISSUE TITLE
Support for icon link tag missing?

### ISSUE THREAD

**Issue by nickg415** [dtrunk90/thymeleaf-jawr-extension#10]
tried both of the following, and neither work

`<link rel="icon" type="image/x-icon" jawr:href="/images/favicon.ico" />`

Gives the following and omits the tag entirely: 2016-03-17 14:35:06,773  WARN AbstractBundleLinkRenderer:102 - No bundle found for path : /images/favicon.ico

`<link rel="icon" type="image/x-icon" jawr:src="/images/favicon.ico" />`

Renders the tag like so (and the favicon does not work):

`<link rel="icon" type="image/x-icon" jawr:src="/images/favicon.ico">`

**Comment by dtrunk90** [comment]
It's new to me that jawr supports favicon. There are 3 supported types: CSS, JS, Binary. As this is neither CSS nor JS I looked into the Jawr ImgHTMLRenderer class. This class only supports `<img />` and `<input type="image" />` tags.

You could open a JIRA ticket [here](http://java.net/jira/browse/JAWR) and ask if supporting favicon is possible.

**Comment by dtrunk90** [comment]
I can try to add a processor for `<link rel="icon" />" tags which uses [this](https://github.com/ic3fox/jawr-main-repo/blob/master/jawr/jawr-core/src/main/java/net/jawr/web/taglib/ImageTagUtils.java#L73) method. But I'm not sure if this will work. It's new to me that Jawr supports favicon.

**Comment by nickg415** [comment]
So to add some context, I'm currently working on migrating from jsp to thymeleaf. What I used to use for favicons was `<link rel="icon" type="image/x-icon" href="<jwr:imagePath src="/images/favicon.ico"/>" />`, where the `jwr:ImagePath` tag is in Jawr's documentation here: https://jawr.java.net/docs/taglibs.html#The_image_tags

Don't know much about Jawr internals, nor Thymeleaf internals, but looks like for JSP's they hook directly into ImageTagUtils.getImageUrl() as you suggested: https://github.com/ic3fox/jawr/blob/master/jawr-core/src/main/java/net/jawr/web/taglib/ImagePathTag.java

So sounds like the approach you described above should do the trick.

**Comment by dtrunk90** [comment]
1.2.0 is released and available next time through maven central repositories. I removed the image attributes as the new expression object will handle image sources. For more information pls take a look at the README.
