### ISSUE TITLE
License

### ISSUE THREAD

**Issue by DeanPoulin** [dtrunk90/thymeleaf-jawr-extension#13]
Would you consider releasing this under the Apache v2 license as JAWR is?

See: https://github.com/j-a-w-r/jawr-main-repo/blob/master/LICENSE

**Comment by dtrunk90** [comment]
I'd consider the Beerware license :-) Usually I don't care about licenses but I'll do it.

**Comment by DeanPoulin** [comment]
👍  Awesome, thanks. Our company has a policy that only allows us to use Apache v2. Really appreciate it and thanks for building this.
