### ISSUE TITLE
debug mode true and gzip false not working

### ISSUE THREAD

**Issue by arapost-bmj** [dtrunk90/thymeleaf-jawr-extension#15]
Hi,

We are using the plugin with spring boot 1.5.1.RELEASE, thymeleaf 3.0.2 release and the latest version of the extension (2.0.1). We have the following problem: 
these properties are ignored completely: 
jawr:
    debug:
        on: true
    gzip:
        on: false

Files are always bundled and gzipped. 
We also tried downgraded spring boot to 1.4.0.RELEASE and tyhmeleaf to 3.0.1, just to test the specific feature (debug true) but it din't work either.

Any ideas of what the problem might be? 

Thank you

**Comment by dtrunk90** [comment]
Hi, I cannot reproduce your issue. Which Jawr version are you using? Try upgrading to 3.9 if necessary. You can take a look into my example webapp [here](https://github.com/dtrunk90/spring-boot-thymeleaf-jawr-demo).

**Comment by arapost-bmj** [comment]
Hi,

Thanks for the response. I managed to solve the problem. It seems was a problem with the yaml format. I had it in the common yaml format: 
jawr:
    debug: 
        on: true
    gzip: 
        on: false
I checked multiple times for indent issues or any other formatting issue, couldn't find anything. When I changed the format in my yaml to the following for jawr properties: 
jawr.debug.on: true
jawr.gzip.on: false
the properties were picked up. It remains a mystery to me, but I can leave with that. 
Thanks, I am closing this issue.

**Comment by arapost-bmj** [comment]
Hi,

Thanks for the response. I managed to solve the problem. It seems was a problem with the yaml format. I had it in the common yaml format: 
jawr:
    debug: 
        on: true
    gzip: 
        on: false
I checked multiple times for indent issues or any other formatting issue, couldn't find anything. When I changed the format in my yaml to the following for jawr properties: 
jawr.debug.on: true
jawr.gzip.on: false
the properties were picked up. It remains a mystery to me, but I can leave with that. 
Thanks, I am closing this issue.

**Comment by dtrunk90** [comment]
Well, that sounds to be a side effect to put all the jawr properties into a map: https://github.com/j-a-w-r/jawr-main-repo/blob/master/jawr-spring/jawr-spring-extension/src/main/java/net/jawr/web/autoconfigure/JawrProperties.java

In the time of writing I was too lazy to write all the possible properties down into that class. Please open up a ticket there. Maybe me or any other will write down all the stuff then to be able to use a correct yaml style.

**Comment by arapost-bmj** [comment]
Thanks, that sounds sensible, I will raise an issue on the repo.
