### ISSUE TITLE
Some default values are overriding properties/attributes

### ISSUE THREAD

**Issue by mullinz** [dtrunk90/thymeleaf-jawr-extension#16]
Just recently upgraded, using 2.0.1, JAWR 3.9, thymeleaf 3.0.5, and spring 3.2.1. And after the migration my jawr:useRandomParam="false" lines within my HTML are no longer working.  No exceptions are thrown but the random hash is still added after my JS files.  Is this something anyone else can reproduce?

I have these settings as follows in my JAWR.properties

jawr.debug.on=true
jawr.debug.use.random.parameter=false

Thanks.

**Comment by dtrunk90** [comment]
If the random hash is still added this is not an issue in thymeleaf jawr extension.

**Comment by mullinz** [comment]
Ok, guess I will have to keep digging then. Are you saying this is not an issue with the thymeleaf jawr extension because I have specified the jawr.debug.use.random.parameter=false in the properties file?

Thanks.

**Comment by dtrunk90** [comment]
Oh, now I understand, sorry. Does the random hash will be added if your set debug to false?

**Comment by mullinz** [comment]
If I set debug=false, as expected I get bundles with files underneath without random numbers added to the files themselves. I.E.

With gzip on..
gzip_101718531/bundles/search.js
With gzip off..
101718531/bundles/search.js

Yet with debug=true, and lines within my HTML like...
<script type="text/javascript" jawr:src="/bundles/searchtools.js" jawr:useRandomParam="false"></script>

I am still seeing the following
/scripts/app/searchtools/searchtools.js?d=94943331

Which breaks browser debugging since upon refresh the file names are regenerated with new numbers.

**Comment by dtrunk90** [comment]
Version 2.0.2 is released and contains the fix. Thanks for the report.

**Comment by mullinz** [comment]
Thanks for the quick turnaround, really appreciate it!
