### ISSUE TITLE
Update Spring and Thymeleaf version

### ISSUE THREAD

**Issue by arulthangaraj** [dtrunk90/thymeleaf-jawr-extension#18]
Hi,

Any plans for new library which supports latest spring boot, spring and thymeleaf versions?

**Comment by dtrunk90** [comment]
New release version will follow asap. Thanks for reporting.

**Comment by dtrunk90** [comment]
Version 2.0.3 is released now supporting Spring Boot 2.0.1.RELEASE and its dependencies.

**Comment by arulthangaraj** [comment]
Thanks Danny, could you please let me know when it will be published to Maven repo?

**Comment by dtrunk90** [comment]
It's published already.

**Comment by arulthangaraj** [comment]
I think probably it takes time to be available to the public. I'm checking the below link and the latest version available to download is 2.0.2

https://mvnrepository.com/artifact/com.github.dtrunk90/thymeleaf-jawr-extension

![image](https://user-images.githubusercontent.com/37940864/38578591-60aa9ed0-3cd2-11e8-96c5-10a83cf9fe10.png)

**Comment by dtrunk90** [comment]
http://search.maven.org/#artifactdetails%7Ccom.github.dtrunk90%7Cthymeleaf-jawr-extension%7C2.0.3%7Cjar

**Comment by dtrunk90** [comment]
FYI: https://github.com/j-a-w-r/jawr-main-repo/pull/81
Until this is merged and released you should exclude and copy the auto configuration in order to adapt the import statement and run your application.

**Comment by arulthangaraj** [comment]
Yes, also jawr is not updated to the latest libraries. I have raised that in the issues not sure when it will be addresses.
Thanks Danny.
