### ISSUE TITLE
jawr.debug.use.random.parameter is not used

### ISSUE THREAD

**Issue by Rafal-Spryszynski** [dtrunk90/thymeleaf-jawr-extension#4]
Random parameter is not used in debug mode.

jawr.debug.use.random.parameter is true by default. It does not matter if I set it or not.

I use net.jawr.debug.on=true and in my configuration I mix Facelets and Thymeleaf. Facelets part use random parameter whereas Thymeleaf does not.

**Comment by dtrunk90** [comment]
Thanks for your report. Version 1.0.3 is released and contains the fix.
