### ISSUE TITLE
Any plans for Thymeleaf 3?

### ISSUE THREAD

**Issue by AlexKovalevich** [dtrunk90/thymeleaf-jawr-extension#7]
Do you have any plans to support Thymeleaf 3?
Thank you

**Comment by dtrunk90** [comment]
Currently not. But I'll take a look at it.

**Comment by dtrunk90** [comment]
I've created a new branch for Thymeleaf 3 migration. It's nearly complete. I just doesn't get the Junit tests to work. The branch will be merged back to master when Thymeleaf 3 has a stable release. Then I'll release a new version as well.

**Comment by AlexKovalevich** [comment]
Sounds great! Really appreciate it!

**Comment by dtrunk90** [comment]
I made some fixes and the unit tests are working now.
I'll let this issue opened in case of missing the release of Thymeleaf 3.

**Comment by stsundermann** [comment]
In the meantime can you upload a beta artifact to maven to use with Thymeleaf 3?

**Comment by dtrunk90** [comment]
2.0.0.BETA01 is released

**Comment by dtrunk90** [comment]
2.0.0.BETA02 is released and compatible to Thymeleaf 3.0.0.BETA03

**Comment by dtrunk90** [comment]
I've released version 2.0.0 which is compatible with Thymeleaf 3.0.0.RELEASE
